### ISSUE TITLE
回答締切後に回答を送信した場合どういう表示になるのか気になる

### ISSUE THREAD

**Issue by kitsunechan** [kamekyame/quiz-web#83]
ポーリングのラグで回答締切後に回答を送信してしまった場合、どうなるのか

回答できてないのに選択できたかのような表示にだけならなければ大丈夫そう

**Comment by kamekyame** [comment]
一瞬は選択されますが、レスポンスがエラーなら前選択したものに変わります。
ということで大丈夫そうなのでClose
